name: Convert Drawio to Image

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Convert diagram file to png image
      uses: ./
      with:
        quality: 100
        scale: 1.0
        src: src/moucnik_diagram.drawio
        dest: diagram.png
    - name: Upload images as artifacts
      uses: actions/upload-artifact@v1
      with:
        name: png
        path: test.png